# api gateway swagger 2.0 yaml-tiedosto Kekkosslovakian postikorttipalvelu

swagger: '2.0'
info:
  title: kekkos-api-testi-1
  description: rajapinta postikorttipalvelulle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

# hae kaikki kortit
paths:
  /all:
    get:
      summary: hakee kaikkien postikorttien tiedot tietokannasta
      operationId: hae-kaikki
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://kirjoita_funktion_url_tähän
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Haku onnistui (hae-kaikki)
          schema:
            type: string
  /single:
    get:
      summary: hakee asiakkaan saaman kortin
      operationId: hae-yksi
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://kirjoita_funktion_url_tähän
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Haku onnistui (hae-yksi)
          schema:
            type: string
    /add:
    post:
      summary: lisää joulukortin järjestelmään
      operationId: lisaa-kortti
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://kirjoita_funktion_url_tähän
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Toiminto onnistui (lisaa-kortti)
          schema:
            type: string

# Jos haluaa api-keyn:
# securityDefinitions:
#   api_key:
#     type: "apiKey"
#     name: "key"
#     in: "query"