# api gateway swagger 2.0 yaml-tiedosto Kekkosslovakian postikorttipalvelu

swagger: '2.0'
info:
  title: kekkos-api-testi-1
  description: rajapinta postikorttipalvelulle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

paths:
  # -------------------------------------------------------------------------------------------------
  # funktio: hae kaikki korttien tiedot tietokannasta ja palauta json-muodossa
  /all:
    get:
      summary: hakee kaikkien postikorttien tiedot tietokannasta
      operationId: hae-kaikki
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://us-central1-final-project-1-337107.cloudfunctions.net/testi-get-all
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Haku onnistui (hae-kaikki)
          schema:
            type: string
  
  # -------------------------------------------------------------------------------------------------
  # funktio: lue yksi kortti -> palauta kortille generoitu html-tiedosto ja merkkaa tietokantaan luetuksi
  /single:
    get:
      summary: hakee asiakkaan saaman kortin
      operationId: hae-yksi
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://us-central1-final-project-1-337107.cloudfunctions.net/testi-get-one
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Haku onnistui (hae-yksi)
          schema:
            type: string
  
  # -------------------------------------------------------------------------------------------------
  # funktio: lisää asiakkaan tilaama kortti tietokantaan:
  /add:
    post:
      summary: lisää joulukortin järjestelmään
      operationId: lisaa-kortti
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos main.py sisältää useamman funktion
        # entrypoint: 
        address: https://us-central1-final-project-1-337107.cloudfunctions.net/testi-postcard
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: Toiminto onnistui (lisaa-kortti)
          schema:
            type: string
    # -------------------------------------------------------------------------------------------------

# Jos haluaa api-keyn:
# securityDefinitions:
#   api_key:
#     type: "apiKey"
#     name: "key"
#     in: "query"